# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'download.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(916, 671)
        Dialog.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.versions = QtWidgets.QTableWidget(Dialog)
        self.versions.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.versions.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.versions.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.versions.setObjectName("versions")
        self.versions.setColumnCount(6)
        self.versions.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.versions.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.versions.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.versions.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.versions.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.versions.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.versions.setHorizontalHeaderItem(5, item)
        self.gridLayout.addWidget(self.versions, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Скачать модификацию"))
        item = self.versions.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Название"))
        item = self.versions.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Версия"))
        item = self.versions.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Тип"))
        item = self.versions.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Загрузчик"))
        item = self.versions.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Скачиваний"))
        item = self.versions.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Размер"))
