# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pack_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.renamePack = QtWidgets.QPushButton(Dialog)
        self.renamePack.setObjectName("renamePack")
        self.horizontalLayout.addWidget(self.renamePack)
        self.deletePack = QtWidgets.QPushButton(Dialog)
        self.deletePack.setObjectName("deletePack")
        self.horizontalLayout.addWidget(self.deletePack)
        self.downloadMods = QtWidgets.QPushButton(Dialog)
        self.downloadMods.setDefault(False)
        self.downloadMods.setFlat(False)
        self.downloadMods.setObjectName("downloadMods")
        self.horizontalLayout.addWidget(self.downloadMods)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.mods = QtWidgets.QListWidget(Dialog)
        self.mods.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.mods.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.mods.setObjectName("mods")
        self.gridLayout.addWidget(self.mods, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Сборка"))
        self.renamePack.setText(_translate("Dialog", "Переименовать сборку"))
        self.deletePack.setText(_translate("Dialog", "Удалить сборку"))
        self.downloadMods.setText(_translate("Dialog", "Скачать моды"))
